#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x5A62D0CAB6264964 (reiter.christoph@gmail.com)
#
Name     : deprecated-pycairo
Version  : 1.17.0
Release  : 27
URL      : https://github.com/pygobject/pycairo/releases/download/v1.17.0/pycairo-1.17.0.tar.gz
Source0  : https://github.com/pygobject/pycairo/releases/download/v1.17.0/pycairo-1.17.0.tar.gz
Source99 : https://github.com/pygobject/pycairo/releases/download/v1.17.0/pycairo-1.17.0.tar.gz.sig
Summary  : Python interface for cairo
Group    : Development/Tools
License  : LGPL-2.1 MPL-1.1
Requires: deprecated-pycairo-license = %{version}-%{release}
Requires: deprecated-pycairo-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pkgconfig(cairo)
BuildRequires : python-dev
Patch1: 0001-Move-pkgconfig-directory-to-usr-lib64-pkgconfig.patch

%description
.. image:: https://cdn.rawgit.com/pygobject/pycairo/master/docs/images/pycairo.svg
:align: center
:width: 370px

%package dev
Summary: dev components for the deprecated-pycairo package.
Group: Development
Provides: deprecated-pycairo-devel = %{version}-%{release}
Requires: deprecated-pycairo = %{version}-%{release}

%description dev
dev components for the deprecated-pycairo package.


%package legacypython
Summary: legacypython components for the deprecated-pycairo package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-pycairo package.


%package license
Summary: license components for the deprecated-pycairo package.
Group: Default

%description license
license components for the deprecated-pycairo package.


%package python
Summary: python components for the deprecated-pycairo package.
Group: Default

%description python
python components for the deprecated-pycairo package.


%prep
%setup -q -n pycairo-1.17.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554325415
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-pycairo
cp COPYING %{buildroot}/usr/share/package-licenses/deprecated-pycairo/COPYING
cp COPYING-LGPL-2.1 %{buildroot}/usr/share/package-licenses/deprecated-pycairo/COPYING-LGPL-2.1
cp COPYING-MPL-1.1 %{buildroot}/usr/share/package-licenses/deprecated-pycairo/COPYING-MPL-1.1
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pycairo/pycairo.h
/usr/lib/python2.7/site-packages/cairo/include/pycairo.h
/usr/lib64/pkgconfig/pycairo.pc

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-pycairo/COPYING
/usr/share/package-licenses/deprecated-pycairo/COPYING-LGPL-2.1
/usr/share/package-licenses/deprecated-pycairo/COPYING-MPL-1.1

%files python
%defattr(-,root,root,-)
